core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('accounts/', include('allauth.urls'))
]
if settings.DEBUG:
    
    urlpatterns+=static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("", views.all_products, name="all_products"),
    path("item/<slug:slug>", views.products_detail, name="products_detail"),
    path("search/<slug:category_slug>", views.category_list, name="category_list"),
    path("add-to-cart/<slug>", views.add_to_cart, name="add_to_cart"),
    path("remove-from-cart/<slug>", views.remove_from_cart, name="remove_from_cart"),
    path(
        "remove-single-item-from-cart/<slug>",
        views.remove_single_item_from_cart,
        name="remove-single-item-from-cart",
    ),
    path("checkout/", views.checkout, name="checkout"),
    path("order-summary", views.order_summary, name="order-summary"),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import PAYMENT_CHOICES
class Category(models.Model):
    name = models.CharField(max_length=255,db_index=True)
    slug = models.SlugField(max_length=255,unique=True)
    class Meta:
        verbose_name_plural = "Categories"# to override "class Category" name in admin panel
    def __str__(self):
        return self.name # to show the objects name in admin panel
    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])
    
class Products(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50,default="admin")
    description = models.TextField(blank=True)
    price = models.FloatField()
    discount_price = models.FloatField(null=True,blank=True)
    image = models.ImageField( upload_to="images/", default="images/default.png")
    slug = models.SlugField(max_length=255)
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name="product_creator", on_delete=models.CASCADE)
    created_time = models.DateTimeField( auto_now_add=True)
    in_stock = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "Products"
        ordering = ('-created_time',)
    def get_absolute_url(self):
        return reverse("store:products_detail", args=[self.slug])
    
    def get_add_to_cart_url(self):
        return reverse("store:add_to_cart",args=[self.slug])
    def get_remove_from_cart_url(self):
        return reverse("store:remove_from_cart",args=[self.slug])
    
    
    def __str__(self):
        return self.title

class OrderProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return self.item.title
    def get_total_product_price(self):
        return self.quantity * self.item.price
    def get_total_discount_product_price(self):
        return self.quantity * self.item.discount_price
    def get_total_amount_saved(self):
        return self.get_total_product_price() - self.get_total_discount_product_price() 
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_product_price()
        else:
            return self.get_total_product_price()
    
    
class Order(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderProduct)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username
    # for showing many to many field in admin panel:
    
    
    def get_items(self):
        return ",".join([str(p) for p in self.items.all()])
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
  
class Address(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    shipping_address = models.CharField(max_length=255)
    shipping_address2 = models.CharField(max_length=255)
    shipping_country = models.CharField( max_length=255)
    shipping_zip = models.CharField(max_length=255)

    billing_address = models.CharField(max_length=255)
    billing_address2 = models.CharField(max_length=255)
    billing_country = models.CharField( max_length=255)
    billing_zip = models.CharField(max_length=255)

    payment_option = models.CharField(max_length=255, choices=PAYMENT_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = "Addresses"

store/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from allauth.account.forms import SignupForm

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

#overriding allauth signup form:
"""class CustomsignupForm(SignupForm):
       def __init__(self, *args, **kwargs):
    # Call the init of the parent class
        super().__init__(*args, **kwargs)
        self.fields[("mobile")] = forms.CharField(required=True)
        #"Rest of your fields"
    # Put in custom signup logic
       def custom_signup(self, request, user):
        # Set the user's type from th form reponse
        user.mobile= self.cleaned_data[("mobile")]
        
      #"Rest of your fields"

        user.save()
        return user"""

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import CheckoutForm
from .models import Products, Category, OrderProduct, Order, Address


# to show categories in every page: you must define category in settings TEMPLATES Options:"store.views.categories"
def categories(request):
   
    return {"categories": Category.objects.all()}


def all_products(request):
    products = Products.objects.filter(in_stock=True)
    return render(request, "home.html", {"products": products})


def products_detail(request, slug):
    product = get_object_or_404(Products, slug=slug)
    return render(request, "detail.html", {"product": product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = Products.objects.filter(category=category)
    return render(request, "category.html", {"category": category, "products": product})


@login_required
def order_summary(request):
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        return render(request, "order-summary.html", {"order": order})
    except ObjectDoesNotExist:
        messages.warning(request, "You do not have an active order")
        return redirect("/")



@login_required
def remove_single_item_from_cart(request, slug):
    product = get_object_or_404(Products, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=product.slug).exists():
            order_item = OrderProduct.objects.filter(
                item=product, user=request.user, ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            # messages.info(request, "This item quantity was updated.")
            return redirect("store:order-summary")
        else:
            # messages.info(request, "This item was not in your cart")
            return redirect("store:products_detail", slug=slug)
    else:
        # messages.info(request, "You do not have an active order")
        return redirect("store:products_detail", slug=slug)


@login_required
def add_to_cart(request, slug):
    product = get_object_or_404(Products, slug=slug)
    order_item, created = OrderProduct.objects.get_or_create(
        item=product, user=request.user, ordered=False
    )
    if Order.objects.filter(user=request.user, ordered=False).exists():
        order = Order.objects.filter(user=request.user, ordered=False)[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            # messages.info(request, "This item quantity was updated.")
            return redirect("store:order-summary")
        else:
            order.items.add(order_item)
            # messages.info(request, "This item was added to your cart.")
            return redirect("store:order-summary")
    else:
        order = Order.objects.create(user=request.user, ordered_date=timezone.now())
        order.items.add(order_item)
        # messages.info(request, "This item was added to your cart.")
        return redirect("store:order-summary")


@login_required
def remove_from_cart(request, slug):
    product = get_object_or_404(Products, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=product.slug).exists():
            order_item = OrderProduct.objects.filter(
                item=product, user=request.user, ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            # messages.info(request, "This item was removed from your cart.")
            return redirect("store:order-summary")
        else:
            # messages.info(request, "This item was not in your cart")
            return redirect("store:products_detail", slug=slug)
    else:
        # messages.info(request, "You do not have an active order")
        return redirect("store:products_detail", slug=slug)


@login_required
def checkout(request):
    if request.method == "POST":
        form = CheckoutForm(request.POST)
        
        if form.is_valid():
            shipping_address = form.cleaned_data["shipping_address"]
            shipping_address2 = form.cleaned_data["shipping_address2"]
            shipping_country = form.cleaned_data["shipping_country"]
            shipping_zip = form.cleaned_data["shipping_zip"]
            billing_address = form.cleaned_data["billing_address"]
            billing_address2 = form.cleaned_data["billing_address2"]
            billing_country = form.cleaned_data["billing_country"]
            billing_zip = form.cleaned_data["billing_zip"]
            payment_options = form.cleaned_data["payment_option"]
            # string all info in backend:
            if Order.objects.filter(user=request.user, ordered=False):
                finalAddress = Address.objects.create(
                    user=request.user,
                    shipping_address=shipping_address,
                    shipping_address2=shipping_address2,
                    shipping_country=shipping_country,
                    shipping_zip=shipping_zip,
                    billing_address=billing_address,
                    billing_address2=billing_address2,
                    billing_country=billing_country,
                    billing_zip=billing_zip,
                    # payment_options = (payment_options),
                    created_at=timezone.now(),
                )
                order = Order.objects.get(user=request.user, ordered=False)
                orderproduct = OrderProduct.objects.get(
                    user=request.user, ordered=False
                )
                orderproduct.ordered = True
                order.ordered = True
                orderproduct.save()
                order.save()

                return redirect("/")
    else:
        form = CheckoutForm()
        if Order.objects.filter(user=request.user, ordered=False):
            return render(request, "checkout.html", {"form": form})

store/templates/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    
    <header>
        
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                {% endfor %}
            {% endif %}
        
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "store:all_products" %}">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:all_products" %}">All</a></li>
                                {% for c in categories %}
                                <li >
                                    <a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name|title}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'store:order-summary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1">{{request.user|cart_item_count}}
                             </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                        
                    </a>
                      
                        <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                          <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                        {% else %}
                        
                          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                          </a>
                        
                          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                          </a>
                        
                    {% endif %}
                    
                    
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock content %}</div>
</body>
</html>

store/templates/category.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9min read</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock content %}

store/templates/checkout.html
{% extends "base.html" %}
{% block content %}
  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}
              

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control pt-4' />
                  <label for="shipping_address" class=" ">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control pt-4' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

             

              </div>

            

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input required type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control pt-4' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control pt-4' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

              

              </div>
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

store/templates/detail.html
{% extends "base.html" %}
{% block title%}
{{product.name}}
{% endblock title%}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{product.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ product.category }}</span>
              </a>
            </div>

            <p class="lead">
              {% if product.discount_price %}
              <span class="mr-1">
                <del>${{ product.price }}</del>
              </span>
              <span>${{ product.discount_price }}</span>
              {% else %}
              <span>${{ product.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ product.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ product.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ product.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

store/templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock title%}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
        <p class="lead text-muted">Best Site For All Men and Women Clothing</p>
        <p>
          <a href="{% url 'account_signup'%}" class="btn btn-primary my-2">Make an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{product.get_absolute_url}}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{product.created_time}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock content %}

store/templates/order-summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in order.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'store:add_to_cart' order_item.item.slug%}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_product_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_total_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_product_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'store:remove_from_cart' order_item.item.slug%}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        
        {% if order.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ order.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}